title: Changes To PIM Settings
id: db6c06c4-bf3b-421c-aa88-15672b88c743
status: experimental
description: Detects when changes are made to PIM roles 
author: Mark Morowczynski '@markmorow', Yochana Henderson, '@Yochana-H'
date: 2022/08/09
references:
    - https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/security-operations-privileged-identity-management#azure-ad-roles-assignment
logsource:
    product: azure
    service: auditlogs
detection:
    selection:
        properties.message: Update role setting in PIM
    condition: selection
falsepositives:
     - Legit administrative PIM setting configuration changes
tags:
    - attack.privilege_escalation
    - attack.defense_evasion
    - attack.t1078
level: high
