/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import { CreateDetectorSteps, MetricsCounter } from '../../types';
import { SecurityAnalyticsApi } from '../models/interfaces';

export enum CLUSTER {
  ADMIN = 'admin',
  SA = 'opensearch_security_analytics',
  DATA = 'data',
}

export const BASE_API_PATH = '/_plugins/_security_analytics';

export const API: SecurityAnalyticsApi = {
  DETECTORS_BASE: `${BASE_API_PATH}/detectors`,
  CORRELATION_BASE: `${BASE_API_PATH}/correlation/rules`,
  SEARCH_DETECTORS: `${BASE_API_PATH}/detectors/_search`,
  INDICES_BASE: `${BASE_API_PATH}/indices`,
  ALIASES_BASE: `${BASE_API_PATH}/aliases`,
  FINDINGS_BASE: `${BASE_API_PATH}/findings`,
  GET_FINDINGS: `${BASE_API_PATH}/findings/_search`,
  DOCUMENT_IDS_QUERY: `${BASE_API_PATH}/document_ids_query`,
  TIME_RANGE_QUERY: `${BASE_API_PATH}/time_range_query`,
  MAPPINGS_BASE: `${BASE_API_PATH}/mappings`,
  MAPPINGS_VIEW: `${BASE_API_PATH}/mappings/view`,
  GET_ALERTS: `${BASE_API_PATH}/alerts`,
  RULES_BASE: `${BASE_API_PATH}/rules`,
  CHANNELS: `${BASE_API_PATH}/_notifications/channels`,
  PLUGINS: `${BASE_API_PATH}/_notifications/plugins`,
  NOTIFICATION_FEATURES: `${BASE_API_PATH}/_notifications/features`,
  ACKNOWLEDGE_ALERTS: `${BASE_API_PATH}/detectors/{detector_id}/_acknowledge/alerts`,
  UPDATE_ALIASES: `${BASE_API_PATH}/update_aliases`,
  CORRELATIONS: `${BASE_API_PATH}/correlations`,
  INTEGRATION_BASE: `${BASE_API_PATH}/integrations`,
  LOGTYPE_BASE: `${BASE_API_PATH}/logtype`,
  KVDBS_BASE: `${BASE_API_PATH}/kvdbs`,
  LOG_TEST_BASE: `${BASE_API_PATH}/logtest`,
  METRICS: `/api/security_analytics/stats`,
  GET_CORRELATION_ALERTS: `${BASE_API_PATH}/correlationAlerts`,
  ACK_CORRELATION_ALERTS: `${BASE_API_PATH}/_acknowledge/correlationAlerts`,
  THREAT_INTEL_BASE: `${BASE_API_PATH}/threat_intel`,
  DECODERS_BASE: `${BASE_API_PATH}/decoders`,
  POLICIES_BASE: `${BASE_API_PATH}/policies`,
};

/**
 * Property with below name is added to the prototype of Opensearch client during setup.
 * @see ../clusters/securityAnalytics/securityAnalyticsPlugin
 */
export const PLUGIN_PROPERTY_NAME: string = 'securityAnalytics';

export const METHOD_NAMES = {
  //Rule methods
  CREATE_RULE: 'createRule',
  DELETE_RULE: 'deleteRule',
  GET_RULE: 'getRule',
  GET_RULES: 'getRules',
  UPDATE_RULE: 'updateRules',

  // Detector methods
  CREATE_DETECTOR: 'createDetector',
  DELETE_DETECTOR: 'deleteDetector',
  GET_DETECTOR: 'getDetector',
  SEARCH_DETECTORS: 'searchDetectors',
  UPDATE_DETECTOR: 'updateDetector',

  // Correlation methods
  GET_CORRELATION_RULES: 'getCorrelationRules',
  CREATE_CORRELATION_RULE: 'createCorrelationRule',
  UPDATE_CORRELATION_RULE: 'updateCorrelationRule',
  DELETE_CORRELATION_RULE: 'deleteCorrelationRule',
  GET_CORRELATED_FINDINGS: 'getCorrelatedFindings',
  GET_ALL_CORRELATIONS: 'getAllCorrelations',
  GET_CORRELATION_ALERTS: 'getAllCorrelationAlerts',
  ACK_CORRELATION_ALERTS: 'acknowledgeCorrelationAlerts',

  // Finding methods
  GET_FINDINGS: 'getFindings',

  // Field mapping methods
  GET_MAPPINGS_VIEW: 'getFieldMappingsView',
  CREATE_MAPPINGS: 'createMappings',
  GET_MAPPINGS: 'getMappings',
  GET_INDEX_ALIAS_MAPPINGS: 'getIndexAliasMappings',

  // Alerts methods
  GET_ALERTS: 'getAlerts',
  ACKNOWLEDGE_ALERTS: 'acknowledgeAlerts',

  // Notifications methods
  GET_CHANNEl: 'getChannel',
  GET_CHANNElS: 'getChannels',
  GET_FEATURES: 'getFeatures',

  // Wazuh: Integration methods
  SEARCH_INTEGRATIONS: 'search',
  CREATE_INTEGRATION: 'createIntegration',
  UPDATE_INTEGRATION: 'updateIntegration',
  DELETE_INTEGRATION: 'deleteIntegration',
  PROMOTE_INTEGRATION: 'promoteIntegration',
  GET_PROMOTE_BY_SPACE: 'getPromoteBySpace',

  //Wazuh: Rule methods
  CREATE_WAZUH_RULE: 'createWazuhRule',
  DELETE_WAZUH_RULE: 'deleteWazuhRule',
  GET_WAZUH_RULE: 'getWazuhRule',
  GET_WAZUH_RULES: 'getWazuhRules',
  UPDATE_WAZUH_RULE: 'updateWazuhRule',

  // Wazuh: Policy methods
  UPDATE_POLICY: 'updatePolicy',

  // LogType methods
  SEARCH_LOGTYPES: 'searchLogTypes',
  CREATE_LOGTYPE: 'createLogType',
  UPDATE_LOGTYPE: 'updateLogType',
  DELETE_LOGTYPE: 'deleteLogType',

  // LogTest methods
  TEST_LOG: 'executeLogtest',

  // Threat intel methods
  ADD_THREAT_INTEL_SOURCE: 'addThreatIntelSource',
  UPDATE_THREAT_INTEL_SOURCE: 'updateThreatIntelSource',
  SEARCH_THREAT_INTEL_SOURCES: 'searchThreatIntelSources',
  GET_THREAT_INTEL_SOURCE: 'getThreatIntelSource',
  DELETE_THREAT_INTEL_SOURCE: 'deleteThreatIntelSource',
  REFRESH_THREAT_INTEL_SOURCE: 'refreshThreatIntelSource',
  GET_THREAT_INTEL_IOCS: 'getThreatIntelIoCs',
  CREATE_THREAT_INTEL_MONITOR: 'createThreatIntelMonitor',
  UPDATE_THREAT_INTEL_MONITOR: 'updateThreatIntelMonitor',
  SEARCH_THREAT_INTEL_MONITORS: 'searchThreatIntelMonitors',
  DELETE_THREAT_INTEL_MONITOR: 'deleteThreatIntelMonitor',
  GET_THREAT_INTEL_FINDINGS: 'getThreatIntelFindings',
  GET_THREAT_INTEL_ALERTS: 'getThreatIntelAlerts',
  UPDATE_THREAT_INTEL_ALERTS_STATE: 'updateThreatIntelAlertsStatus',

  // Decoder methods
  CREATE_DECODER: 'createDecoder',
  UPDATE_DECODER: 'updateDecoder',
  DELETE_DECODER: 'deleteDecoder',

  // KVDB methods
  CREATE_KVDB: 'createKvdb',
  UPDATE_KVDB: 'updateKvdb',
  DELETE_KVDB: 'deleteKvdb',
};

/**
 * These methods are defined on the Opensearch client instance by adding them to the client's
 * prototype under the @see PLUGIN_PROPERTY_NAME field.
 * @see ../clusters/securityAnalytics/securityAnalyticsPlugin
 */
export const CLIENT_RULE_METHODS = {
  // Wazuh: use wazuh rule methods
  CREATE_RULE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.CREATE_WAZUH_RULE}`,
  DELETE_RULE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.DELETE_WAZUH_RULE}`,
  GET_RULE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_WAZUH_RULE}`,
  GET_RULES: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_WAZUH_RULES}`,
  UPDATE_RULE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.UPDATE_WAZUH_RULE}`,
};

export const CLIENT_DETECTOR_METHODS = {
  CREATE_DETECTOR: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.CREATE_DETECTOR}`,
  DELETE_DETECTOR: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.DELETE_DETECTOR}`,
  GET_DETECTOR: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_DETECTOR}`,
  SEARCH_DETECTORS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.SEARCH_DETECTORS}`,
  UPDATE_DETECTOR: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.UPDATE_DETECTOR}`,
  GET_FINDINGS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_FINDINGS}`,
};

export const CLIENT_CORRELATION_METHODS = {
  GET_CORRELATION_RULES: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_CORRELATION_RULES}`,
  CREATE_CORRELATION_RULE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.CREATE_CORRELATION_RULE}`,
  UPDATE_CORRELATION_RULE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.UPDATE_CORRELATION_RULE}`,
  DELETE_CORRELATION_RULE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.DELETE_CORRELATION_RULE}`,
  GET_CORRELATED_FINDINGS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_CORRELATED_FINDINGS}`,
  GET_ALL_CORRELATIONS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_ALL_CORRELATIONS}`,
  GET_CORRELATION_ALERTS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_CORRELATION_ALERTS}`,
  ACK_CORRELATION_ALERTS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.ACK_CORRELATION_ALERTS}`,
};

export const CLIENT_FIELD_MAPPINGS_METHODS = {
  GET_MAPPINGS_VIEW: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_MAPPINGS_VIEW}`,
  CREATE_MAPPINGS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.CREATE_MAPPINGS}`,
  GET_MAPPINGS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_MAPPINGS}`,
  GET_INDEX_ALIAS_MAPPINGS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_INDEX_ALIAS_MAPPINGS}`,
};

export const CLIENT_ALERTS_METHODS = {
  ACKNOWLEDGE_ALERTS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.ACKNOWLEDGE_ALERTS}`,
  GET_ALERTS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_ALERTS}`,
};

export const CLIENT_NOTIFICATIONS_METHODS = {
  GET_CHANNEL: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_CHANNEl}`,
  GET_CHANNELS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_CHANNElS}`,
  GET_FEATURES: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_FEATURES}`,
};

export const CLIENT_LOGTYPE_METHODS = {
  SEARCH_LOGTYPES: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.SEARCH_LOGTYPES}`,
  CREATE_LOGTYPE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.CREATE_LOGTYPE}`,
  UPDATE_LOGTYPE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.UPDATE_LOGTYPE}`,
  DELETE_LOGTYPE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.DELETE_LOGTYPE}`,
};

// Wazuh
export const CLIENT_INTEGRATION_METHODS = {
  SEARCH_INTEGRATIONS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.SEARCH_INTEGRATIONS}`,
  CREATE_INTEGRATION: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.CREATE_INTEGRATION}`,
  UPDATE_INTEGRATION: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.UPDATE_INTEGRATION}`,
  DELETE_INTEGRATION: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.DELETE_INTEGRATION}`,
  PROMOTE_INTEGRATION: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.PROMOTE_INTEGRATION}`,
  GET_PROMOTE_BY_SPACE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_PROMOTE_BY_SPACE}`,
};

// Wazuh
export const CLIENT_POLICY_METHODS = {
  UPDATE_POLICY: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.UPDATE_POLICY}`,
};

export const CLIENT_LOG_TEST_METHODS = {
  TEST_LOG: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.TEST_LOG}`,
};

export const CLIENT_THREAT_INTEL_METHODS = {
  ADD_THREAT_INTEL_SOURCE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.ADD_THREAT_INTEL_SOURCE}`,
  UPDATE_THREAT_INTEL_SOURCE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.UPDATE_THREAT_INTEL_SOURCE}`,
  SEARCH_THREAT_INTEL_SOURCES: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.SEARCH_THREAT_INTEL_SOURCES}`,
  GET_THREAT_INTEL_SOURCE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_THREAT_INTEL_SOURCE}`,
  DELETE_THREAT_INTEL_SOURCE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.DELETE_THREAT_INTEL_SOURCE}`,
  REFRESH_THREAT_INTEL_SOURCE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.REFRESH_THREAT_INTEL_SOURCE}`,
  GET_THREAT_INTEL_IOCS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_THREAT_INTEL_IOCS}`,
  CREATE_THREAT_INTEL_MONITOR: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.CREATE_THREAT_INTEL_MONITOR}`,
  UPDATE_THREAT_INTEL_MONITOR: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.UPDATE_THREAT_INTEL_MONITOR}`,
  SEARCH_THREAT_INTEL_MONITORS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.SEARCH_THREAT_INTEL_MONITORS}`,
  DELETE_THREAT_INTEL_MONITOR: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.DELETE_THREAT_INTEL_MONITOR}`,
  GET_THREAT_INTEL_FINDINGS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_THREAT_INTEL_FINDINGS}`,
  GET_THREAT_INTEL_ALERTS: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.GET_THREAT_INTEL_ALERTS}`,
  UPDATE_THREAT_INTEL_ALERTS_STATE: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.UPDATE_THREAT_INTEL_ALERTS_STATE}`,
};

export const CLIENT_DECODER_METHODS = {
  CREATE_DECODER: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.CREATE_DECODER}`,
  UPDATE_DECODER: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.UPDATE_DECODER}`,
  DELETE_DECODER: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.DELETE_DECODER}`,
};

export const CLIENT_KVDB_METHODS = {
  CREATE_KVDB: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.CREATE_KVDB}`,
  UPDATE_KVDB: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.UPDATE_KVDB}`,
  DELETE_KVDB: `${PLUGIN_PROPERTY_NAME}.${METHOD_NAMES.DELETE_KVDB}`,
};

export const DEFAULT_METRICS_COUNTER: MetricsCounter = {
  CreateDetector: {
    [CreateDetectorSteps.started]: 0,
    [CreateDetectorSteps.sourceSelected]: 0,
    [CreateDetectorSteps.rulesConfigured]: 0,
    [CreateDetectorSteps.fieldMappingsConfigured]: 0,
    [CreateDetectorSteps.threatIntelConfigured]: 0,
    [CreateDetectorSteps.stepTwoInitiated]: 0,
    [CreateDetectorSteps.triggerConfigured]: 0,
    [CreateDetectorSteps.createClicked]: 0,
  },
};

export const CONTENT_MANAGER_BASE_PATH = '/_plugins/_content_manager';
